// Personal Dashboard Progress Tracker Styles
export const defaultStyles = {
  wrapper: "bg-white rounded-xl shadow-lg p-6",
  heading: "flex items-center text-lg font-display font-semibold mb-4 text-neutral-dark",
  headingIcon: "w-5 h-5 mr-2 text-primary",
  headingText: "",
  section: "space-y-4",
  overallLabel: "text-sm font-sans font-bold text-neutral-secondary-light",
  overallValue: "text-sm font-display font-bold text-primary",
  barContainer: "w-full bg-neutral-secondary-light rounded-full h-3 overflow-hidden",
  barFill: "bg-primary h-3 rounded-full",
  gridSection: "grid grid-cols-2 gap-4 pt-4",
  completedCard: "flex flex-col items-center justify-center p-4 rounded-lg cursor-pointer bg-success-light transition-all",
  remainingCard: "flex flex-col items-center justify-center p-4 rounded-lg cursor-pointer bg-primary-light transition-all",
  statIconCompleted: "w-6 h-6 mb-2 text-success",
  statIconRemaining: "w-6 h-6 mb-2 text-primary",
  statValue: "text-2xl font-display font-bold text-neutral-dark",
  statLabel: "text-sm font-sans text-neutral-dark",
  currentSection: "pt-4 border-t border-neutral-secondary-light",
  currentLabel: "flex items-center text-sm font-sans font-medium text-neutral-secondary-light mb-1",
  currentValue: "flex items-center text-sm font-sans text-neutral-dark",
  currentValueIcon: "w-4 h-4 mr-2 text-accent",
};

// Team Dashboard Progress Tracker Styles
export const teamStyles = {
  wrapper: "bg-white bg-opacity-70 backdrop-blur-sm rounded-2xl shadow-md p-6 border border-purple-200",
  heading: "flex items-center text-lg font-semibold mb-4",
  headingIcon: "w-5 h-5 mr-2 text-purple-600",
  headingText: "bg-gradient-to-r from-[#380A63] to-[#5E35B1] bg-clip-text text-transparent",
  section: "space-y-5",
  overallLabel: "text-sm font-sans font-bold text-[#380A63]/80",
  overallValue: "text-sm font-bold bg-gradient-to-r from-[#380A63] to-[#5E35B1] bg-clip-text text-transparent",
  barContainer: "w-full bg-purple-100 rounded-full h-3 overflow-hidden shadow-inner",
  barFill: "bg-gradient-to-r from-purple-600 to-purple-800 h-3 rounded-full",
  gridSection: "grid grid-cols-2 gap-4 pt-4",
  completedCard: "flex flex-col items-center justify-center p-4 rounded-xl cursor-pointer bg-gradient-to-br from-[#EDE7F6] to-[#D1C4E9]/80 border border-[#D1C4E9] transition-all hover:scale-105 transition-transform duration-200",
  remainingCard: "flex flex-col items-center justify-center p-4 rounded-xl cursor-pointer bg-gradient-to-br from-[#EDE7F6] to-[#C5CAE9]/70 border border-[#D1C4E9] transition-all hover:scale-105 transition-transform duration-200",
  statIconCompleted: "w-6 h-6 mb-2 text-purple-600",
  statIconRemaining: "w-6 h-6 mb-2 text-purple-600",
  statValue: "text-2xl font-bold bg-gradient-to-r from-[#380A63] to-[#5E35B1] bg-clip-text text-transparent",
  statLabel: "text-sm font-sans text-[#380A63]/80",
  currentSection: "pt-4 border-t border-purple-200",
  currentLabel: "flex items-center text-sm font-sans font-medium text-[#380A63]/70 mb-1",
  currentValue: "flex items-center font-semibold text-[#380A63]",
  currentValueIcon: "w-4 h-4 mr-2 text-purple-600",
};