"""
Module Insertion Schema
======================

This module contains the state schema and data models for the module insertion workflow.
It defines the structure and validation for data flowing through the LangGraph workflow.

Key Components:
- ModuleInsertionState: Main state schema for the workflow
- Validation and serialization helpers
- Type definitions and constraints
"""

from typing import Dict, Any, List, Optional
from datetime import datetime
from pydantic import BaseModel, Field, field_validator
from app.models.enums import DifficultyLevel, LearningStyle, ExperienceLevel


class ModuleInsertionState(BaseModel):
    """
    State schema for module insertion workflow.

    This class defines all the data that flows through the LangGraph workflow
    for inserting modules into learning paths. It includes input parameters,
    intermediate processing data, and final results.

    Enhanced with dictionary-like operations for LangGraph compatibility.
    """

    # =============================================================================
    # INPUT PARAMETERS (Required)
    # =============================================================================

    user_query: str = Field(..., description="What the user wants in the module")
    learning_path_id: int = Field(..., description="Target learning path ID")
    insert_position: int = Field(..., ge=0, description="Index where the new module will be inserted")
    platform_name: str = Field(..., description="Platform to use for content")
    user_id: str = Field(..., description="User performing the insertion")

    # =============================================================================
    # LEARNING PATH INFORMATION (Retrieved during workflow)
    # =============================================================================

    learning_path_title: Optional[str] = Field(None, description="Title of the learning path")
    experience_level: Optional[ExperienceLevel] = Field(None, description="User's experience level")
    goals: Optional[str] = Field(None, description="Learning goals from preferences")
    path_title: Optional[str] = Field(None, description="Alias for learning_path_title")
    path_description: Optional[str] = Field(None, description="Learning path description")
    existing_modules: List[Dict[str, Any]] = Field(default_factory=list, description="Existing modules in the path")

    # =============================================================================
    # MODULE GENERATION DATA
    # =============================================================================

    module_difficulty: Optional[DifficultyLevel] = Field(None, description="Difficulty level for new module")
    current_difficulty: Optional[str] = Field(None, description="Current difficulty level being processed")
    current_module_index: int = Field(default=1, description="Current module being processed")
    generated_module: Dict[str, Any] = Field(default_factory=dict, description="Generated module data")
    module_queries: List[str] = Field(default_factory=list, description="Generated queries for content search")
    content_pool: List[Dict[str, Any]] = Field(default_factory=list, description="Pool of available content")
    selected_content: Optional[Dict[str, Any]] = Field(None, description="Selected content for module")
    platform_queries: Dict[str, Any] = Field(default_factory=dict,
                                             description="Platform-specific queries generated by QueryGenerationService")

    # =============================================================================
    # WORKFLOW STATE MANAGEMENT
    # =============================================================================

    current_stage: str = Field(default="initialization", description="Current workflow stage")
    stage_start_time: datetime = Field(default_factory=datetime.now, description="When current stage started")
    total_start_time: datetime = Field(default_factory=datetime.now, description="When workflow started")
    error_message: Optional[str] = Field(None, description="Primary error message if workflow fails")
    created_module_id: Optional[int] = Field(None, description="ID of created module")
    preferences_id: Optional[int] = Field(None, description="ID of user preferences")

    # =============================================================================
    # ADDITIONAL METADATA AND CONFIGURATION
    # =============================================================================

    performance_metrics: Dict[str, Any] = Field(default_factory=dict, description="Performance tracking data")
    debug_info: Dict[str, Any] = Field(default_factory=dict, description="Debug information")
    generation_config: Dict[str, Any] = Field(default_factory=dict, description="Generation configuration")
    generation_started_at: Optional[datetime] = Field(None, description="When generation started")
    generation_summary: Dict[str, Any] = Field(default_factory=dict, description="Generation summary")

    # =============================================================================
    # NOTIFICATION AND COMMUNICATION
    # =============================================================================

    notification_recipients: List[str] = Field(default_factory=list, description="Users to notify")

    # =============================================================================
    # LEARNING AND STYLE PREFERENCES
    # =============================================================================

    learning_styles: List[LearningStyle] = Field(default_factory=list, description="Preferred learning styles")
    learning_objectives: List[str] = Field(default_factory=list, description="Learning objectives for module")

    # =============================================================================
    # PLATFORM AND CONTENT MANAGEMENT
    # =============================================================================

    llm_context: Optional[str] = Field(None, description="LLM context for generation")
    max_retries: int = Field(default=3, description="Maximum retry attempts")
    estimated_days: Optional[int] = Field(None, description="Estimated days for completion")
    errors: List[str] = Field(default_factory=list, description="List of errors encountered")

    class Config:
        """Pydantic configuration."""
        arbitrary_types_allowed = True
        use_enum_values = True
        validate_assignment = True

    # =============================================================================
    # DICTIONARY-LIKE OPERATIONS FOR LANGGRAPH COMPATIBILITY
    # =============================================================================

    def __getitem__(self, key: str) -> Any:
        """Support dict-like access: state['key']"""
        if hasattr(self, key):
            return getattr(self, key)
        raise KeyError(f"'{key}' not found in ModuleInsertionState")

    def __setitem__(self, key: str, value: Any) -> None:
        """Support dict-like assignment: state['key'] = value"""
        if hasattr(self, key):
            setattr(self, key, value)
        else:
            # For dynamic fields, add them to debug_info or as new attributes
            setattr(self, key, value)

    def __contains__(self, key: str) -> bool:
        """Support 'key in state' checks"""
        return hasattr(self, key)

    def get(self, key: str, default: Any = None) -> Any:
        """Support dict.get() method"""
        try:
            return self[key]
        except KeyError:
            return default

    def keys(self):
        """Support dict.keys() method"""
        return self.__dict__.keys()

    def items(self):
        """Support dict.items() method"""
        return self.__dict__.items()

    def values(self):
        """Support dict.values() method"""
        return self.__dict__.values()

    def update(self, other: Dict[str, Any]) -> None:
        """Support dict.update() method"""
        for key, value in other.items():
            self[key] = value

    # =============================================================================
    # EXISTING METHODS
    # =============================================================================

    def to_dict(self) -> Dict[str, Any]:
        """
        Convert the state to a dictionary for LangGraph compatibility.

        Returns:
            Dict representation of the state
        """
        return self.model_dump(exclude_none=False, by_alias=True)

    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> "ModuleInsertionState":
        """
        Create state from dictionary data.

        Args:
            data: Dictionary data to convert

        Returns:
            ModuleInsertionState instance
        """
        return cls(**data)

    def update_stage(self, stage: str, stage_data: Optional[Dict[str, Any]] = None) -> None:
        """
        Update the current stage and related metadata.

        Args:
            stage: New stage name
            stage_data: Optional additional data for the stage
        """
        self.current_stage = stage
        self.stage_start_time = datetime.now()

        if stage_data:
            for key, value in stage_data.items():
                if hasattr(self, key):
                    setattr(self, key, value)

    def add_error(self, error: str) -> None:
        """
        Add an error to the error list.

        Args:
            error: Error message to add
        """
        self.errors.append(error)
        if not self.error_message:
            self.error_message = error

    def has_errors(self) -> bool:
        """
        Check if the state has any errors.

        Returns:
            True if there are errors, False otherwise
        """
        return bool(self.error_message or self.errors)

    def get_execution_time(self) -> Optional[float]:
        """
        Calculate total execution time if workflow has started.

        Returns:
            Execution time in seconds, or None if not started
        """
        if self.total_start_time:
            return (datetime.now() - self.total_start_time).total_seconds()
        return None

    def get_stage_time(self) -> Optional[float]:
        """
        Calculate current stage execution time.

        Returns:
            Stage execution time in seconds, or None if no stage started
        """
        if self.stage_start_time:
            return (datetime.now() - self.stage_start_time).total_seconds()
        return None


class ModuleInsertionRequest(BaseModel):
    """
    Request schema for module insertion API endpoint.
    """

    user_query: str = Field(..., min_length=1, max_length=500, description="What the user wants in the module")
    learning_path_id: int = Field(..., gt=0, description="Target learning path ID")
    insert_position: int = Field(..., ge=0, description="Index where the new module will be inserted")
    platform_name: str = Field(..., description="Platform to use for content")

    class Config:
        """Pydantic configuration."""
        json_schema_extra = {
            "example": {
                "user_query": "Introduction to machine learning algorithms",
                "learning_path_id": 123,
                "insert_position": 2,
                "platform_name": "youtube"
            }
        }


class ModuleInsertionResponse(BaseModel):
    """
    Response schema for module insertion API endpoint.
    """

    success: bool = Field(..., description="Whether the insertion was successful")
    created_module_id: Optional[int] = Field(None, description="ID of the created module")
    module_title: Optional[str] = Field(None, description="Title of the created module")
    execution_time_seconds: Optional[float] = Field(None, description="Total execution time")
    stages_completed: Optional[str] = Field(None, description="Last completed stage")
    error: Optional[str] = Field(None, description="Error message if failed")

    class Config:
        """Pydantic configuration."""
        json_schema_extra = {
            "example": {
                "success": True,
                "created_module_id": 456,
                "module_title": "Introduction to Machine Learning Algorithms",
                "execution_time_seconds": 15.7,
                "stages_completed": "completed",
                "error": None
            }
        }


# =============================================================================
# TYPE ALIASES AND HELPERS
# =============================================================================

ModuleInsertionStateDict = Dict[str, Any]
"""Type alias for module insertion state as dictionary."""

def create_initial_state(
    user_query: str,
    learning_path_id: int,
    insert_position: int,
    platform_name: str,
    user_id: str,
    **kwargs
) -> ModuleInsertionState:
    """
    Create initial state for module insertion workflow.

    Args:
        user_query: What the user wants in the module
        learning_path_id: Target learning path ID
        insert_position: Index where the new module will be inserted
        platform_name: Platform to use for content
        user_id: User performing the insertion
        **kwargs: Additional state parameters

    Returns:
        Initialized ModuleInsertionState
    """
    state_data = {
        "user_query": user_query,
        "learning_path_id": learning_path_id,
        "insert_position": insert_position,
        "platform_name": platform_name,
        "user_id": user_id,
        "current_stage": "initialization",
        "total_start_time": datetime.now(),
        "stage_start_time": datetime.now(),
        **kwargs
    }

    return ModuleInsertionState(**state_data)


def validate_platform_name(platform_name: str) -> bool:
    """
    Validate if platform name is supported.

    Args:
        platform_name: Platform name to validate

    Returns:
        True if platform is supported, False otherwise
    """
    supported_platforms = ["youtube", "spotify", "google books", "semantic scholar", "codeforces"]
    return platform_name.lower() in supported_platforms


class ModuleInsertionAsyncRequest(ModuleInsertionRequest):
    """Request model for asynchronous module insertion."""

    priority: Optional[str] = Field("normal", description="Task priority: low, normal, high")
    callback_url: Optional[str] = Field(None, description="Optional webhook URL for completion notification")

    @field_validator('platform_name')
    def validate_platform(cls, v):
        if not validate_platform_name(v):
            supported = ["youtube", "spotify", "google books", "semantic scholar", "codeforces"]
            raise ValueError(f"Platform '{v}' not supported. Supported platforms: {supported}")
        return v.lower()

    @field_validator('priority')
    def validate_priority(cls, v):
        if v not in ["low", "normal", "high"]:
            raise ValueError("Priority must be one of: low, normal, high")
        return v


class AsyncInsertionResponse(BaseModel):
    """Response model for asynchronous module insertion."""

    task_id: str = Field(..., description="Task ID for tracking")
    status: str = Field(..., description="Initial task status")
    message: str = Field(..., description="Status message")
    estimated_completion_time: Optional[str] = Field(None, description="Estimated completion time")
